# Generated by Django 6.0.2 on 2026-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('space_left', models.DecimalField(decimal_places=20, default=5368709120, max_digits=20)),
            ],
        ),
    ]
