# Generated by Django 6.0.2 on 2026-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='space_left',
            field=models.DecimalField(decimal_places=2, default=5368709120, max_digits=15),
        ),
    ]
