# Generated by Django 6.0.2 on 2026-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='space_left',
            field=models.DecimalField(decimal_places=20, default=5368709120, max_digits=20, null=True),
        ),
    ]
