# Generated by Django 6.0.2 on 2026-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='space_left',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
