# Generated by Django 6.0.2 on 2026-02-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_space_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('space_left', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
